name: Release

on:
  release:
    types: [created]

jobs:
  arm64:
    name: Release Go Binary arm64
    runs-on: [self-hosted, arm64]
    steps:
      - uses: actions/checkout@v2
      - name: Build bor
        run: |
          make bor
          cd ./build/bin/
          tar -czvf bor-$(basename ${GITHUB_REF})-linux-arm64.tar.gz bor
          echo $(md5sum bor | awk '{print $1}') > bor-$(basename ${GITHUB_REF})-linux-arm64.tar.gz.md5
      - name: Upload bor to release page
        run: |
          github-assets-uploader -logtostderr -f cmd/geth/bor-$(basename ${GITHUB_REF})-linux-arm64.tar.gz -mediatype application/gzip -repo ${GITHUB_REPOSITORY} -token ${{ secrets.GITHUB_TOKEN }} -tag=$(basename ${GITHUB_REF}) -releasename="" -retry 3
          github-assets-uploader -logtostderr -f cmd/geth/bor-$(basename ${GITHUB_REF})-linux-arm64.tar.gz.md5 -mediatype text/plain -repo ${GITHUB_REPOSITORY} -token ${{ secrets.GITHUB_TOKEN }} -tag=$(basename ${GITHUB_REF}) -releasename="" -retry 3
      - name: Build bootnode
        run: |
          cd cmd/bootnode && /opt/go/1.19.5/bin/go build
          tar -czvf bootnode-$(basename ${GITHUB_REF})-linux-arm64.tar.gz bootnode
          echo $(md5sum bootnode | awk '{print $1}') > bootnode-$(basename ${GITHUB_REF})-linux-arm64.tar.gz.md5
      - name: Upload bootnode to release page
        run: |
          github-assets-uploader -logtostderr -f cmd/bootnode/bootnode-$(basename ${GITHUB_REF})-linux-arm64.tar.gz -mediatype application/gzip -repo ${GITHUB_REPOSITORY} -token ${{ secrets.GITHUB_TOKEN }} -tag=$(basename ${GITHUB_REF}) -releasename="" -retry 3
          github-assets-uploader -logtostderr -f cmd/bootnode/bootnode-$(basename ${GITHUB_REF})-linux-arm64.tar.gz.md5 -mediatype text/plain -repo ${GITHUB_REPOSITORY} -token ${{ secrets.GITHUB_TOKEN }} -tag=$(basename ${GITHUB_REF}) -releasename="" -retry 3

  amd64:
    name: Release Go Binary amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20.5' # The Go version to download (if necessary) and use.
      - name: Build bor
        run: |
          make bor
          cd ./build/bin/
          tar -czvf bor-$(basename ${GITHUB_REF})-linux-amd64.tar.gz bor
          echo $(md5sum bor | awk '{print $1}') > bor-$(basename ${GITHUB_REF})-linux-amd64.tar.gz.md5
      - name: Upload bor to release page
        run: |
          github-assets-uploader -logtostderr -f cmd/geth/bor-$(basename ${GITHUB_REF})-linux-amd64.tar.gz -mediatype application/gzip -repo ${GITHUB_REPOSITORY} -token ${{ secrets.GITHUB_TOKEN }} -tag=$(basename ${GITHUB_REF}) -releasename="" -retry 3
          github-assets-uploader -logtostderr -f cmd/geth/bor-$(basename ${GITHUB_REF})-linux-amd64.tar.gz.md5 -mediatype text/plain -repo ${GITHUB_REPOSITORY} -token ${{ secrets.GITHUB_TOKEN }} -tag=$(basename ${GITHUB_REF}) -releasename="" -retry 3
      - name: Build bootnode
        run: |
          cd cmd/bootnode && go build
          tar -czvf bootnode-$(basename ${GITHUB_REF})-linux-amd64.tar.gz bootnode
          echo $(md5sum bootnode | awk '{print $1}') > bootnode-$(basename ${GITHUB_REF})-linux-amd64.tar.gz.md5
      - name: Upload bootnode to release page
        run: |
          github-assets-uploader -logtostderr -f cmd/bootnode/bootnode-$(basename ${GITHUB_REF})-linux-amd64.tar.gz -mediatype application/gzip -repo ${GITHUB_REPOSITORY} -token ${{ secrets.GITHUB_TOKEN }} -tag=$(basename ${GITHUB_REF}) -releasename="" -retry 3
          github-assets-uploader -logtostderr -f cmd/bootnode/bootnode-$(basename ${GITHUB_REF})-linux-amd64.tar.gz.md5 -mediatype text/plain -repo ${GITHUB_REPOSITORY} -token ${{ secrets.GITHUB_TOKEN }} -tag=$(basename ${GITHUB_REF}) -releasename="" -retry 3
